//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailerDaemon2
{
    using System;
    using System.Collections.Generic;
    
    public partial class application
    {
        public int id { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public int UserID { get; set; }
        public string ApplicationGUID { get; set; }
        public string ApplicationKey { get; set; }
        public string MailDomain { get; set; }
        public string MailAddress { get; set; }
        public string MailUsername { get; set; }
        public string MailPassword { get; set; }
        public string MailServiceUrl { get; set; }
        public int IsActive { get; set; }
        public int DaemonPort { get; set; }
    }
}
