//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailerDaemon2
{
    using System;
    using System.Collections.Generic;
    
    public partial class appmailrecipient
    {
        public int id { get; set; }
        public int AppMailID { get; set; }
        public string To { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastUpdated { get; set; }
    
        public virtual appmail appmail { get; set; }
    }
}
