//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailerGUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appmailagent
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string domain { get; set; }
        public int port { get; set; }
        public string mailingaddress { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastUpdated { get; set; }
        public int isActive { get; set; }
    }
}
