//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIC.MailerDaemon.Client.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class appmail
    {
        public appmail()
        {
            this.appmailattachments = new HashSet<appmailattachment>();
            this.appmailbccs = new HashSet<appmailbcc>();
            this.appmailccs = new HashSet<appmailcc>();
            this.appmailrecipients = new HashSet<appmailrecipient>();
        }
    
        public int id { get; set; }
        public int ApplicationID { get; set; }
        public string From { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public int Retries { get; set; }
        public int isSent { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateLastUpdated { get; set; }
        public string UID { get; set; }
    
        public virtual ICollection<appmailattachment> appmailattachments { get; set; }
        public virtual ICollection<appmailbcc> appmailbccs { get; set; }
        public virtual ICollection<appmailcc> appmailccs { get; set; }
        public virtual ICollection<appmailrecipient> appmailrecipients { get; set; }
    }
}
