//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMIC.MailerDaemon.Client.API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mailerdaemonEntities : DbContext
    {
        public mailerdaemonEntities()
            : base("name=mailerdaemonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<application> applications { get; set; }
        public DbSet<appmailattachment> appmailattachments { get; set; }
        public DbSet<appmailbcc> appmailbccs { get; set; }
        public DbSet<appmailcc> appmailccs { get; set; }
        public DbSet<appmailjob> appmailjobs { get; set; }
        public DbSet<appmailrecipient> appmailrecipients { get; set; }
        public DbSet<appmail> appmails { get; set; }
        public DbSet<counter> counters { get; set; }
        public DbSet<distributedlock> distributedlocks { get; set; }
        public DbSet<hash> hashes { get; set; }
        public DbSet<job> jobs { get; set; }
        public DbSet<jobparameter> jobparameters { get; set; }
        public DbSet<jobqueue> jobqueues { get; set; }
        public DbSet<jobstate> jobstates { get; set; }
        public DbSet<list> lists { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<server> servers { get; set; }
        public DbSet<set> sets { get; set; }
        public DbSet<user> users { get; set; }
    }
}
